# Flask後端安裝說明

print("=== Flask後端安裝與運行說明 ===")
print()
print("1. 創建虛擬環境:")
print("   python -m venv venv")
print("   source venv/bin/activate  # Linux/Mac")
print("   venv\\Scripts\\activate     # Windows")
print()
print("2. 安裝依賴套件:")
print("   pip install flask flask-socketio flask-cors")
print("   pip install opencv-python mediapipe numpy")
print("   pip install python-socketio eventlet")
print()
print("3. 運行Flask後端:")
print("   python flask-backend.py")
print()
print("4. 確認服務運行:")
print("   瀏覽器開啟: http://localhost:5000")
print("   WebSocket連接: ws://localhost:5000")
print()
print("5. 前端環境變數設定:")
print("   NEXT_PUBLIC_API_URL=http://localhost:5000")
print()
print("=== 功能特色 ===")
print("✅ MediaPipe姿勢檢測")
print("✅ 即時骨架渲染")
print("✅ WebSocket串流")
print("✅ 影片上傳分析")
print("✅ 攝像機即時分析")
print("✅ 分析數據統計")
print("✅ 歷史記錄保存")
